"""add resume fields and per-interview max_questions

Revision ID: bc1bd691fa72
Revises: 6aec087192f8
Create Date: 2026-07-23 21:51:47.589513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1bd691fa72'
down_revision: Union[str, Sequence[str], None] = '6aec087192f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('max_questions', sa.Integer(), nullable=False))
    op.add_column('interviews', sa.Column('resume_text', sa.Text(), nullable=False))
    op.add_column('interviews', sa.Column('resume_blob_name', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'resume_blob_name')
    op.drop_column('interviews', 'resume_text')
    op.drop_column('interviews', 'max_questions')
    # ### end Alembic commands ###
